/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as InviteTokenRouteImport } from "./routes/invite.$token"
import { Route as AuthCallbackRouteImport } from "./routes/auth.callback"
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated.dashboard"
import { Route as AuthenticatedTripsTripIdRouteImport } from "./routes/_authenticated.trips.$tripId"
import { Route as AuthenticatedTripsTripIdReservationsRouteImport } from "./routes/_authenticated.trips.$tripId.reservations"
import { Route as AuthenticatedTripsTripIdMembersRouteImport } from "./routes/_authenticated.trips.$tripId.members"
import { Route as AuthenticatedTripsTripIdItineraryRouteImport } from "./routes/_authenticated.trips.$tripId.itinerary"
import { Route as AuthenticatedTripsTripIdFilesRouteImport } from "./routes/_authenticated.trips.$tripId.files"
import { Route as AuthenticatedTripsTripIdChecklistsRouteImport } from "./routes/_authenticated.trips.$tripId.checklists"
import { Route as AuthenticatedTripsTripIdBudgetRouteImport } from "./routes/_authenticated.trips.$tripId.budget"

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: "/trips/$tripId",
    path: "/trips/$tripId",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsTripIdReservationsRoute =
  AuthenticatedTripsTripIdReservationsRouteImport.update({
    id: "/reservations",
    path: "/reservations",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdMembersRoute =
  AuthenticatedTripsTripIdMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdItineraryRoute =
  AuthenticatedTripsTripIdItineraryRouteImport.update({
    id: "/itinerary",
    path: "/itinerary",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdFilesRoute =
  AuthenticatedTripsTripIdFilesRouteImport.update({
    id: "/files",
    path: "/files",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdChecklistsRoute =
  AuthenticatedTripsTripIdChecklistsRouteImport.update({
    id: "/checklists",
    path: "/checklists",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdBudgetRoute =
  AuthenticatedTripsTripIdBudgetRouteImport.update({
    id: "/budget",
    path: "/budget",
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/trips/$tripId": typeof AuthenticatedTripsTripIdRouteWithChildren
  "/trips/$tripId/budget": typeof AuthenticatedTripsTripIdBudgetRoute
  "/trips/$tripId/checklists": typeof AuthenticatedTripsTripIdChecklistsRoute
  "/trips/$tripId/files": typeof AuthenticatedTripsTripIdFilesRoute
  "/trips/$tripId/itinerary": typeof AuthenticatedTripsTripIdItineraryRoute
  "/trips/$tripId/members": typeof AuthenticatedTripsTripIdMembersRoute
  "/trips/$tripId/reservations": typeof AuthenticatedTripsTripIdReservationsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/trips/$tripId": typeof AuthenticatedTripsTripIdRouteWithChildren
  "/trips/$tripId/budget": typeof AuthenticatedTripsTripIdBudgetRoute
  "/trips/$tripId/checklists": typeof AuthenticatedTripsTripIdChecklistsRoute
  "/trips/$tripId/files": typeof AuthenticatedTripsTripIdFilesRoute
  "/trips/$tripId/itinerary": typeof AuthenticatedTripsTripIdItineraryRoute
  "/trips/$tripId/members": typeof AuthenticatedTripsTripIdMembersRoute
  "/trips/$tripId/reservations": typeof AuthenticatedTripsTripIdReservationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/_authenticated/trips/$tripId": typeof AuthenticatedTripsTripIdRouteWithChildren
  "/_authenticated/trips/$tripId/budget": typeof AuthenticatedTripsTripIdBudgetRoute
  "/_authenticated/trips/$tripId/checklists": typeof AuthenticatedTripsTripIdChecklistsRoute
  "/_authenticated/trips/$tripId/files": typeof AuthenticatedTripsTripIdFilesRoute
  "/_authenticated/trips/$tripId/itinerary": typeof AuthenticatedTripsTripIdItineraryRoute
  "/_authenticated/trips/$tripId/members": typeof AuthenticatedTripsTripIdMembersRoute
  "/_authenticated/trips/$tripId/reservations": typeof AuthenticatedTripsTripIdReservationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/auth/callback"
    | "/invite/$token"
    | "/trips/$tripId"
    | "/trips/$tripId/budget"
    | "/trips/$tripId/checklists"
    | "/trips/$tripId/files"
    | "/trips/$tripId/itinerary"
    | "/trips/$tripId/members"
    | "/trips/$tripId/reservations"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard"
    | "/auth/callback"
    | "/invite/$token"
    | "/trips/$tripId"
    | "/trips/$tripId/budget"
    | "/trips/$tripId/checklists"
    | "/trips/$tripId/files"
    | "/trips/$tripId/itinerary"
    | "/trips/$tripId/members"
    | "/trips/$tripId/reservations"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_authenticated/dashboard"
    | "/auth/callback"
    | "/invite/$token"
    | "/_authenticated/trips/$tripId"
    | "/_authenticated/trips/$tripId/budget"
    | "/_authenticated/trips/$tripId/checklists"
    | "/_authenticated/trips/$tripId/files"
    | "/_authenticated/trips/$tripId/itinerary"
    | "/_authenticated/trips/$tripId/members"
    | "/_authenticated/trips/$tripId/reservations"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/callback": {
      id: "/auth/callback"
      path: "/auth/callback"
      fullPath: "/auth/callback"
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/trips/$tripId": {
      id: "/_authenticated/trips/$tripId"
      path: "/trips/$tripId"
      fullPath: "/trips/$tripId"
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/trips/$tripId/reservations": {
      id: "/_authenticated/trips/$tripId/reservations"
      path: "/reservations"
      fullPath: "/trips/$tripId/reservations"
      preLoaderRoute: typeof AuthenticatedTripsTripIdReservationsRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    "/_authenticated/trips/$tripId/members": {
      id: "/_authenticated/trips/$tripId/members"
      path: "/members"
      fullPath: "/trips/$tripId/members"
      preLoaderRoute: typeof AuthenticatedTripsTripIdMembersRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    "/_authenticated/trips/$tripId/itinerary": {
      id: "/_authenticated/trips/$tripId/itinerary"
      path: "/itinerary"
      fullPath: "/trips/$tripId/itinerary"
      preLoaderRoute: typeof AuthenticatedTripsTripIdItineraryRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    "/_authenticated/trips/$tripId/files": {
      id: "/_authenticated/trips/$tripId/files"
      path: "/files"
      fullPath: "/trips/$tripId/files"
      preLoaderRoute: typeof AuthenticatedTripsTripIdFilesRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    "/_authenticated/trips/$tripId/checklists": {
      id: "/_authenticated/trips/$tripId/checklists"
      path: "/checklists"
      fullPath: "/trips/$tripId/checklists"
      preLoaderRoute: typeof AuthenticatedTripsTripIdChecklistsRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    "/_authenticated/trips/$tripId/budget": {
      id: "/_authenticated/trips/$tripId/budget"
      path: "/budget"
      fullPath: "/trips/$tripId/budget"
      preLoaderRoute: typeof AuthenticatedTripsTripIdBudgetRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
  }
}

interface AuthenticatedTripsTripIdRouteChildren {
  AuthenticatedTripsTripIdBudgetRoute: typeof AuthenticatedTripsTripIdBudgetRoute
  AuthenticatedTripsTripIdChecklistsRoute: typeof AuthenticatedTripsTripIdChecklistsRoute
  AuthenticatedTripsTripIdFilesRoute: typeof AuthenticatedTripsTripIdFilesRoute
  AuthenticatedTripsTripIdItineraryRoute: typeof AuthenticatedTripsTripIdItineraryRoute
  AuthenticatedTripsTripIdMembersRoute: typeof AuthenticatedTripsTripIdMembersRoute
  AuthenticatedTripsTripIdReservationsRoute: typeof AuthenticatedTripsTripIdReservationsRoute
}

const AuthenticatedTripsTripIdRouteChildren: AuthenticatedTripsTripIdRouteChildren =
  {
    AuthenticatedTripsTripIdBudgetRoute: AuthenticatedTripsTripIdBudgetRoute,
    AuthenticatedTripsTripIdChecklistsRoute:
      AuthenticatedTripsTripIdChecklistsRoute,
    AuthenticatedTripsTripIdFilesRoute: AuthenticatedTripsTripIdFilesRoute,
    AuthenticatedTripsTripIdItineraryRoute:
      AuthenticatedTripsTripIdItineraryRoute,
    AuthenticatedTripsTripIdMembersRoute: AuthenticatedTripsTripIdMembersRoute,
    AuthenticatedTripsTripIdReservationsRoute:
      AuthenticatedTripsTripIdReservationsRoute,
  }

const AuthenticatedTripsTripIdRouteWithChildren =
  AuthenticatedTripsTripIdRoute._addFileChildren(
    AuthenticatedTripsTripIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
